USE master;
GO
ALTER DATABASE msdb
MODIFY FILE (NAME = MSDBData, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\MSDBData.mdf');
GO
ALTER DATABASE msdb
MODIFY FILE (NAME = MSDBLog, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\MSDBLog.ldf');
GO

ALTER DATABASE model
MODIFY FILE (NAME = modeldev, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\model.mdf');
GO
ALTER DATABASE model
MODIFY FILE (NAME = modellog, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\modellog.ldf');
GO

ALTER DATABASE tempdb
MODIFY FILE (NAME = tempdev, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\tempdb.mdf');
GO
ALTER DATABASE tempdb
MODIFY FILE (NAME = templog, FILENAME = '\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\templog.ldf');
GO

FOR RECOVERY FROM MISSING SYSTEM DBs
D:\Program Files\Microsoft SQL Server\MSSQL11.ECCQA\MSSQL\Binn
SQLServr.exe -s ECCQA -f -e\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\Log\ERRORLOG -d\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\master.mdf -l\\SVM-HV01\SQL_ECCQ_SQLSystemDB\MSSQL11.ECCQA\MSSQL\DATA\mastlog.ldf -T7806 -T3608 -T3609