--Create the temporary table for surnames and populate it
create table #surnames( id int IDENTITY(1,1) NOT NULL, surname nvarchar(50) NULL,
	CONSTRAINT [PK_surnames] PRIMARY KEY CLUSTERED (id asc))

insert into #surnames (surname) values ('Smith')
insert into #surnames (surname) values ('Jones')
insert into #surnames (surname) values ('Taylor')
insert into #surnames (surname) values ('Williams')
insert into #surnames (surname) values ('Brown')
insert into #surnames (surname) values ('Davies')
insert into #surnames (surname) values ('Evans')
insert into #surnames (surname) values ('Wilson')
insert into #surnames (surname) values ('Thomas')
insert into #surnames (surname) values ('Roberts')
insert into #surnames (surname) values ('Johnson')
insert into #surnames (surname) values ('Lewis')
insert into #surnames (surname) values ('Walker')
insert into #surnames (surname) values ('Robinson')
insert into #surnames (surname) values ('Wood')
insert into #surnames (surname) values ('Thompson')
insert into #surnames (surname) values ('White')
insert into #surnames (surname) values ('Watson')
insert into #surnames (surname) values ('Jackson')
insert into #surnames (surname) values ('Wright')
insert into #surnames (surname) values ('Green')
insert into #surnames (surname) values ('Harris')
insert into #surnames (surname) values ('Cooper')
insert into #surnames (surname) values ('King')
insert into #surnames (surname) values ('Lee')
insert into #surnames (surname) values ('Martin')
insert into #surnames (surname) values ('Clarke')
insert into #surnames (surname) values ('James')
insert into #surnames (surname) values ('Morgan')
insert into #surnames (surname) values ('Hughes')
insert into #surnames (surname) values ('Edwards')
insert into #surnames (surname) values ('Hill')
insert into #surnames (surname) values ('Moore')
insert into #surnames (surname) values ('Clark')
insert into #surnames (surname) values ('Harrison')
insert into #surnames (surname) values ('Scott')
insert into #surnames (surname) values ('Young')
insert into #surnames (surname) values ('Morris')
insert into #surnames (surname) values ('Hall')
insert into #surnames (surname) values ('Ward')
insert into #surnames (surname) values ('Turner')
insert into #surnames (surname) values ('Carter')
insert into #surnames (surname) values ('Phillips')
insert into #surnames (surname) values ('Mitchell')
insert into #surnames (surname) values ('Patel')
insert into #surnames (surname) values ('Adams')
insert into #surnames (surname) values ('Campbell')
insert into #surnames (surname) values ('Anderson')
insert into #surnames (surname) values ('Allen')
insert into #surnames (surname) values ('Cook')
insert into #surnames (surname) values ('Bailey')
insert into #surnames (surname) values ('Parker')
insert into #surnames (surname) values ('Miller')
insert into #surnames (surname) values ('Davis')
insert into #surnames (surname) values ('Murphy')
insert into #surnames (surname) values ('Price')
insert into #surnames (surname) values ('Bell')
insert into #surnames (surname) values ('Baker')
insert into #surnames (surname) values ('Griffiths')
insert into #surnames (surname) values ('Kelly')
insert into #surnames (surname) values ('Simpson')
insert into #surnames (surname) values ('Marshall')
insert into #surnames (surname) values ('Collins')
insert into #surnames (surname) values ('Bennett')
insert into #surnames (surname) values ('Cox')
insert into #surnames (surname) values ('Richardson')
insert into #surnames (surname) values ('Fox')
insert into #surnames (surname) values ('Gray')
insert into #surnames (surname) values ('Rose')
insert into #surnames (surname) values ('Chapman')
insert into #surnames (surname) values ('Hunt')
insert into #surnames (surname) values ('Robertson')
insert into #surnames (surname) values ('Shaw')
insert into #surnames (surname) values ('Reynolds')
insert into #surnames (surname) values ('Lloyd')
insert into #surnames (surname) values ('Ellis')
insert into #surnames (surname) values ('Richards')
insert into #surnames (surname) values ('Russell')
insert into #surnames (surname) values ('Wilkinson')
insert into #surnames (surname) values ('Khan')
insert into #surnames (surname) values ('Graham')
insert into #surnames (surname) values ('Stewart')
insert into #surnames (surname) values ('Reid')
insert into #surnames (surname) values ('Murray')
insert into #surnames (surname) values ('Powell')
insert into #surnames (surname) values ('Palmer')
insert into #surnames (surname) values ('Holmes')
insert into #surnames (surname) values ('Rogers')
insert into #surnames (surname) values ('Stevens')
insert into #surnames (surname) values ('Walsh')
insert into #surnames (surname) values ('Hunter')
insert into #surnames (surname) values ('Thomson')
insert into #surnames (surname) values ('Matthews')
insert into #surnames (surname) values ('Ross')
insert into #surnames (surname) values ('Owen')
insert into #surnames (surname) values ('Mason')
insert into #surnames (surname) values ('Knight')
insert into #surnames (surname) values ('Kennedy')
insert into #surnames (surname) values ('Butler')
insert into #surnames (surname) values ('Saunders')
insert into #surnames (surname) values ('Cole')
insert into #surnames (surname) values ('Pearce')
insert into #surnames (surname) values ('Dean')
insert into #surnames (surname) values ('Foster')
insert into #surnames (surname) values ('Harvey')
insert into #surnames (surname) values ('Hudson')
insert into #surnames (surname) values ('Gibson')
insert into #surnames (surname) values ('Mills')
insert into #surnames (surname) values ('Berry')
insert into #surnames (surname) values ('Barnes')
insert into #surnames (surname) values ('Pearson')
insert into #surnames (surname) values ('Kaur')
insert into #surnames (surname) values ('Booth')
insert into #surnames (surname) values ('Dixon')
insert into #surnames (surname) values ('Grant')
insert into #surnames (surname) values ('Gordon')
insert into #surnames (surname) values ('Lane')
insert into #surnames (surname) values ('Harper')
insert into #surnames (surname) values ('Ali')
insert into #surnames (surname) values ('Hart')
insert into #surnames (surname) values ('Mcdonald')
insert into #surnames (surname) values ('Brooks')
insert into #surnames (surname) values ('Ryan')
insert into #surnames (surname) values ('Carr')
insert into #surnames (surname) values ('Macdonald')
insert into #surnames (surname) values ('Hamilton')
insert into #surnames (surname) values ('Johnston')
insert into #surnames (surname) values ('West')
insert into #surnames (surname) values ('Gill')
insert into #surnames (surname) values ('Dawson')
insert into #surnames (surname) values ('Armstrong')
insert into #surnames (surname) values ('Gardner')
insert into #surnames (surname) values ('Stone')
insert into #surnames (surname) values ('Andrews')
insert into #surnames (surname) values ('Williamson')
insert into #surnames (surname) values ('Barker')
insert into #surnames (surname) values ('George')
insert into #surnames (surname) values ('Fisher')
insert into #surnames (surname) values ('Cunningham')
insert into #surnames (surname) values ('Watts')
insert into #surnames (surname) values ('Webb')
insert into #surnames (surname) values ('Lawrence')
insert into #surnames (surname) values ('Bradley')
insert into #surnames (surname) values ('Jenkins')
insert into #surnames (surname) values ('Wells')
insert into #surnames (surname) values ('Chambers')
insert into #surnames (surname) values ('Spencer')
insert into #surnames (surname) values ('Poole')
insert into #surnames (surname) values ('Atkinson')
insert into #surnames (surname) values ('Lawson')


--Create the temporary table for forenames and populate it
create table #forenames ( id int IDENTITY(1,1) NOT NULL, forename nvarchar(50) null, 
	CONSTRAINT [PK_FORNAMES] PRIMARY KEY CLUSTERED (id asc) )

insert into #forenames (forename) values ('Jack')
insert into #forenames (forename) values ('Thomas')
insert into #forenames (forename) values ('James')
insert into #forenames (forename) values ('Daniel')
insert into #forenames (forename) values ('Joshua')
insert into #forenames (forename) values ('Matthew')
insert into #forenames (forename) values ('Samuel')
insert into #forenames (forename) values ('Callum')
insert into #forenames (forename) values ('Joseph')
insert into #forenames (forename) values ('Jordan')
insert into #forenames (forename) values ('Connor')
insert into #forenames (forename) values ('Ryan')
insert into #forenames (forename) values ('Luke')
insert into #forenames (forename) values ('William')
insert into #forenames (forename) values ('Harry')
insert into #forenames (forename) values ('Benjamin')
insert into #forenames (forename) values ('George')
insert into #forenames (forename) values ('Lewis')
insert into #forenames (forename) values ('Alexander')
insert into #forenames (forename) values ('Oliver')
insert into #forenames (forename) values ('Adam')
insert into #forenames (forename) values ('Jake')
insert into #forenames (forename) values ('Michael')
insert into #forenames (forename) values ('Liam')
insert into #forenames (forename) values ('Nathan')
insert into #forenames (forename) values ('Kieran')
insert into #forenames (forename) values ('Jacob')
insert into #forenames (forename) values ('Cameron')
insert into #forenames (forename) values ('Ben')
insert into #forenames (forename) values ('Aaron')
insert into #forenames (forename) values ('Christopher')
insert into #forenames (forename) values ('Bradley')
insert into #forenames (forename) values ('Jamie')
insert into #forenames (forename) values ('Mohammed')
insert into #forenames (forename) values ('Charlie')
insert into #forenames (forename) values ('Brandon')
insert into #forenames (forename) values ('Robert')
insert into #forenames (forename) values ('Kyle')
insert into #forenames (forename) values ('David')
insert into #forenames (forename) values ('Owen')
insert into #forenames (forename) values ('Charles')
insert into #forenames (forename) values ('Andrew')
insert into #forenames (forename) values ('Reece')
insert into #forenames (forename) values ('Edward')
insert into #forenames (forename) values ('Dylan')
insert into #forenames (forename) values ('Alex')
insert into #forenames (forename) values ('Ethan')
insert into #forenames (forename) values ('Jonathan')
insert into #forenames (forename) values ('Sam')
insert into #forenames (forename) values ('Louis')
insert into #forenames (forename) values ('Max')
insert into #forenames (forename) values ('Dominic')
insert into #forenames (forename) values ('John')
insert into #forenames (forename) values ('Ashley')
insert into #forenames (forename) values ('Rhys')
insert into #forenames (forename) values ('Henry')
insert into #forenames (forename) values ('Conor')
insert into #forenames (forename) values ('Joe')
insert into #forenames (forename) values ('Tyler')
insert into #forenames (forename) values ('Scott')
insert into #forenames (forename) values ('Sean')
insert into #forenames (forename) values ('Nicholas')
insert into #forenames (forename) values ('Ross')
insert into #forenames (forename) values ('Morgan')
insert into #forenames (forename) values ('Elliot')
insert into #forenames (forename) values ('Patrick')
insert into #forenames (forename) values ('Peter')
insert into #forenames (forename) values ('Billy')
insert into #forenames (forename) values ('Mark')
insert into #forenames (forename) values ('Stephen')
insert into #forenames (forename) values ('Alfie')
insert into #forenames (forename) values ('Harrison')
insert into #forenames (forename) values ('Lee')
insert into #forenames (forename) values ('Anthony')
insert into #forenames (forename) values ('Mitchell')
insert into #forenames (forename) values ('Joel')
insert into #forenames (forename) values ('Toby')
insert into #forenames (forename) values ('Paul')
insert into #forenames (forename) values ('Jay')
insert into #forenames (forename) values ('Jason')
insert into #forenames (forename) values ('Aidan')
insert into #forenames (forename) values ('Richard')
insert into #forenames (forename) values ('Isaac')
insert into #forenames (forename) values ('Declan')
insert into #forenames (forename) values ('Mohammad')
insert into #forenames (forename) values ('Josh')
insert into #forenames (forename) values ('Steven')
insert into #forenames (forename) values ('Marcus')
insert into #forenames (forename) values ('Elliott')
insert into #forenames (forename) values ('Harvey')
insert into #forenames (forename) values ('Muhammad')
insert into #forenames (forename) values ('Tom')
insert into #forenames (forename) values ('Christian')
insert into #forenames (forename) values ('Kane')
insert into #forenames (forename) values ('Shane')
insert into #forenames (forename) values ('Leon')
insert into #forenames (forename) values ('Shaun')
insert into #forenames (forename) values ('Corey')
insert into #forenames (forename) values ('Ellis')
insert into #forenames (forename) values ('Kai')
insert into #forenames (forename) values ('Chloe')
insert into #forenames (forename) values ('Emily')
insert into #forenames (forename) values ('Megan')
insert into #forenames (forename) values ('Jessica')
insert into #forenames (forename) values ('Sophie')
insert into #forenames (forename) values ('Charlotte')
insert into #forenames (forename) values ('Hannah')
insert into #forenames (forename) values ('Lauren')
insert into #forenames (forename) values ('Rebecca')
insert into #forenames (forename) values ('Lucy')
insert into #forenames (forename) values ('Amy')
insert into #forenames (forename) values ('Georgia')
insert into #forenames (forename) values ('Katie')
insert into #forenames (forename) values ('Bethany')
insert into #forenames (forename) values ('Emma')
insert into #forenames (forename) values ('Olivia')
insert into #forenames (forename) values ('Courtney')
insert into #forenames (forename) values ('Shannon')
insert into #forenames (forename) values ('Eleanor')
insert into #forenames (forename) values ('Jade')
insert into #forenames (forename) values ('Ellie')
insert into #forenames (forename) values ('Abigail')
insert into #forenames (forename) values ('Holly')
insert into #forenames (forename) values ('Molly')
insert into #forenames (forename) values ('Laura')
insert into #forenames (forename) values ('Alice')
insert into #forenames (forename) values ('Sarah')
insert into #forenames (forename) values ('Caitlin')
insert into #forenames (forename) values ('Rachel')
insert into #forenames (forename) values ('Amber')
insert into #forenames (forename) values ('Elizabeth')
insert into #forenames (forename) values ('Paige')
insert into #forenames (forename) values ('Georgina')
insert into #forenames (forename) values ('Danielle')
insert into #forenames (forename) values ('Grace')
insert into #forenames (forename) values ('Nicole')
insert into #forenames (forename) values ('Natasha')
insert into #forenames (forename) values ('Ella')
insert into #forenames (forename) values ('Chelsea')
insert into #forenames (forename) values ('Leah')
insert into #forenames (forename) values ('Victoria')
insert into #forenames (forename) values ('Anna')
insert into #forenames (forename) values ('Phoebe')
insert into #forenames (forename) values ('Samantha')
insert into #forenames (forename) values ('Zoe')
insert into #forenames (forename) values ('Alexandra')
insert into #forenames (forename) values ('Jasmine')
insert into #forenames (forename) values ('Amelia')
insert into #forenames (forename) values ('Louise')
insert into #forenames (forename) values ('Lydia')
insert into #forenames (forename) values ('Natalie')
insert into #forenames (forename) values ('Abbie')
insert into #forenames (forename) values ('Francesca')
insert into #forenames (forename) values ('Melissa')
insert into #forenames (forename) values ('Katherine')
insert into #forenames (forename) values ('Harriet')
insert into #forenames (forename) values ('Imogen')
insert into #forenames (forename) values ('Jodie')
insert into #forenames (forename) values ('Gemma')
insert into #forenames (forename) values ('Kayleigh')
insert into #forenames (forename) values ('Lily')
insert into #forenames (forename) values ('Jennifer')
insert into #forenames (forename) values ('Kate')
insert into #forenames (forename) values ('Stephanie')
insert into #forenames (forename) values ('Daisy')
insert into #forenames (forename) values ('Niamh')
insert into #forenames (forename) values ('Millie')
insert into #forenames (forename) values ('Aimee')
insert into #forenames (forename) values ('Kirsty')
insert into #forenames (forename) values ('Hollie')
insert into #forenames (forename) values ('Rosie')
insert into #forenames (forename) values ('Jordan')
insert into #forenames (forename) values ('Mollie')
insert into #forenames (forename) values ('Alisha')
insert into #forenames (forename) values ('Mia')
insert into #forenames (forename) values ('Isobel')
insert into #forenames (forename) values ('Tia')
insert into #forenames (forename) values ('Ellen')
insert into #forenames (forename) values ('Erin')
insert into #forenames (forename) values ('Bethan')
insert into #forenames (forename) values ('Alicia')
insert into #forenames (forename) values ('Sian')
insert into #forenames (forename) values ('Rhiannon')
insert into #forenames (forename) values ('Ashleigh')
insert into #forenames (forename) values ('Catherine')
insert into #forenames (forename) values ('Madeleine')
insert into #forenames (forename) values ('Isabelle')
insert into #forenames (forename) values ('Kelsey')
insert into #forenames (forename) values ('Sophia')
insert into #forenames (forename) values ('Isabella')
insert into #forenames (forename) values ('Naomi')
insert into #forenames (forename) values ('Freya')
insert into #forenames (forename) values ('Robyn')
insert into #forenames (forename) values ('Morgan')
insert into #forenames (forename) values ('Yasmin')
insert into #forenames (forename) values ('Isabel')
insert into #forenames (forename) values ('Maisie')
insert into #forenames (forename) values ('Poppy')
insert into #forenames (forename) values ('Rachael')
insert into #forenames (forename) values ('Chantelle')
--select * from #forenames

--declare the variables we'll use
declare @surname varchar(50)
declare @forename varchar(50)
declare @newSurname varchar(50)
declare @newForename varchar(50)
declare @id int

--build a cursor to select the contents of PERSON_NAMES one line at a time
declare  names_cursor cursor for
select pna_uid, first_names, last_name from person_names

open names_cursor
fetch next from names_cursor into @id, @forename, @surname

--while we have entires in the table, iterate
while @@fetch_status = 0
begin
	--generate our random surname and forename
	select @newSurname = (select top 1 surname from #surnames order by newid())
	select @newForename = (select top 1 forename from #forenames order by newid())
	
	--update the table with the new names
	--update person_names set first_names = @newSurname where pna_uid = @id
	--update person_names set last_name = @newForename where pna_uid = @id
	--update person_names set match_first_names = upper(@newSurname) where pna_uid = @id
	--update person_names set match_last_name = upper(@newForename) where pna_uid = @id

	update person_names set
		first_names = @newForename, last_name = @newSurname,
		match_first_names = upper(@newForename), match_last_name = upper(@newSurname)
		where pna_uid = @id

	--iterate through the table
	fetch next from names_cursor into @id, @forename, @surname
end

--deallocate the stuff we've built
close names_cursor
deallocate names_cursor
drop table #forenames
drop table #surnames